# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-06 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
