# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20190903_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumcomment',
            old_name='description',
            new_name='comment',
        ),
    ]
