# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190808_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
    ]
