# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_feature_comment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='desc',
            new_name='description',
        ),
    ]
