# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20190903_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurecomment',
            old_name='description',
            new_name='comment',
        ),
    ]
