# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0009_auto_20190903_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
