# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0010_auto_20190904_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
